import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextFont } from "next/dist/compiled/@next/font";

import { Oswald } from "next/font/google";

const oswald = Oswald({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={""} data-theme="dark">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
